-- This file is automatically generated, do not edit!
return {
  ["JewelAccuracy"] = { type = "Prefix", affix = "Accurate", "(5-10)% increased Accuracy Rating", statOrder = { 1332 }, level = 1, group = "IncreasedAccuracyPercent", weightKey = { "dexjewel", "jewel", }, weightVal = { 1, 0 }, modTags = { "attack" }, },
  ["JewelAttackSpeed"] = { type = "Suffix", affix = "of Alacrity", "(2-4)% increased Attack Speed", statOrder = { 985 }, level = 1, group = "IncreasedAttackSpeed", weightKey = { "dexjewel", "jewel", }, weightVal = { 1, 0 }, modTags = { "attack", "speed" }, },
  ["JewelChaosDamage"] = { type = "Prefix", affix = "Chaotic", "(7-13)% increased Chaos Damage", statOrder = { 876 }, level = 1, group = "IncreasedChaosDamage", weightKey = { "intjewel", "jewel", }, weightVal = { 1, 0 }, modTags = { "chaos_damage", "damage", "chaos" }, },
}
