"use strict";
const fs=require("node:fs"),test=require("node:test"),assert=require("node:assert/strict"),path=require("node:path"); const {report,reportAllocationCoverage}=require("../tools/report-passive-id-coverage.cjs");
const repositoryRoot=path.resolve(__dirname,"..","..",".."),workspaceRoot=path.dirname(repositoryRoot),lock=path.join(repositoryRoot,"data","upstream-sources.lock.json");
const configuredCache=process.env.POE2_VALIDATED_CACHE_DIR;
const cache=path.resolve(configuredCache||path.join(workspaceRoot,"P2AT-004C-acceptance","user-data","game-data","core"));
const requiredCacheFiles=["official-data.json","tree-pre.json"];
function requireValidatedCache(t){const missing=requiredCacheFiles.filter(file=>!fs.existsSync(path.join(cache,file)));if(!missing.length)return true;const message=`validated cache unavailable at ${cache}; missing ${missing.join(", ")}`;if(configuredCache)assert.fail(message);t.skip(message);return false;}
test("locked coverage reports real mappings, categories, and Zarokh conflict",t=>{if(!requireValidatedCache(t))return;const r=report(cache,lock);assert.equal(r.officialNodeCount,5153);assert.equal(r.treePreNodeCount,5102);assert.equal(r.numericIntersection,5102);assert.equal(r.mappedIntersection,4863);assert.equal(r.categories.normal.candidateCount,4483);assert.equal(r.categories.normal.mappedCount,4483);assert.equal(r.categories.ascendancy.candidateCount,669);assert.equal(r.categories.ascendancy.mappedCount,429);assert.equal(r.categories.ordinaryJewelSockets.mappedCount,12);assert.equal(r.categories.specialSockets.mappedCount,7);assert.equal(r.conflict11184.official,"DeliriumAnoint_ZarokhsGift_");assert.deepEqual(r.knownMappings,[{status:"mapped",numericId:"2491",officialId:"jewel_slot1974"},{status:"mapped",numericId:"7960",officialId:"jewel_slot1969"},{status:"mapped",numericId:"26725",officialId:"jewel_slot1956"},{status:"mapped",numericId:"17788",officialId:"AscendancyWitch3Notable1"},{status:"mapped",numericId:"11184",officialId:"DeliriumAnoint_ZarokhsGift_"}]);assert.equal(r.categories.weaponSet.classificationStatus,"unverified");assert.equal(r.categories.instilledHidden.classificationStatus,"unverified");});
test("allocation coverage evaluates supplied native allocation",t=>{if(!requireValidatedCache(t))return;const official=JSON.parse(fs.readFileSync(path.join(cache,"official-data.json"),"utf8")),r=reportAllocationCoverage(official,["2491","7960","missing"]);assert.equal(r.candidateCount,3);assert.equal(r.mappedCount,2);assert.equal(r.missingCount,1);assert.deepEqual(r.unmappedIds,["missing"]);});
